replicaCount: 1
image:
  repository: muthukumarse/myapp
  tag: d3e8eb9fc3dc69a0f9125e2c7b78e3bd1e6e1688
  pullPolicy: IfNotPresent
service:
  name: myapp
  type: ClusterIP
  externalPort: 80
  internalPort: 8080