name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: latest
        service_account_key: ${{ env.GOOGLE_CREDENTIALS }}

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: 3.4.0

    - name: Deploy Release on cluster
      run: |
        helm upgrade --install myapp ./
