name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GKE_CLUSTER: silent-oxygen-376712-gke
  GKE_REGION: asia-southeast1 
  GKE_PROJECT: silent-oxygen-376712
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: latest
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        
    - name: Deploy
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --region $GKE_REGION \
          --project $GKE_PROJECT
        helm upgrade --install myapp ./ \
          --wait
